name = "ChipFiring"
uuid = "be096eff-6f16-4fe8-bf2d-b0d7a78a4be0"
authors = ["Vincent Wang <vw12@rice.edu>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
Combinatorics = "1.0.3"
DataStructures = "0.18.22"
